2020-12-21 14:56:35,710 INFO: App startup... [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/app/__init__.py:28]
2020-12-21 14:56:57,814 ERROR: Exception on /edit_profile [POST] [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/app/routes.py", line 85, in edit_profile
    db.session.commit()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
    self._flush(objects)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
    flush_context.execute()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 230, in save_obj
    _emit_update_statements(
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 994, in _emit_update_statements
    c = cached_connections[connection].execute(
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('geexmmo', '', 4)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
