2021-01-13 01:26:12,332 ERROR: Exception on /login [GET] [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/app/routes.py", line 42, in login
    return render_template('login.html', title='Login', form=form, links=links)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/app/templates/base.html", line 13, in template
    {% elif Not current_user.is_authenticated %}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got 'current_user'
2021-01-13 01:26:31,421 INFO: App startup... [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/app/__init__.py:28]
2021-01-13 01:26:32,259 ERROR: Exception on /login [GET] [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/app/routes.py", line 42, in login
    return render_template('login.html', title='Login', form=form, links=links)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/app/templates/base.html", line 17, in template
    {% else %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'else'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endif'. The innermost block that needs to be closed is 'if'.
2021-01-13 01:30:13,149 INFO: App startup... [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/app/__init__.py:28]
2021-01-13 01:31:23,604 INFO: App startup... [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/app/__init__.py:28]
2021-01-13 01:31:58,987 INFO: App startup... [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/app/__init__.py:28]
2021-01-13 01:31:59,867 ERROR: Exception on /login [GET] [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/app/routes.py", line 42, in login
    return render_template('login.html', title='Login', form=form, links=links)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/app/templates/base.html", line 14, in top-level template code
    [<a href="{{ url_for(login) }}">{{ link.name }}</a>: Login first]
  File "/home/geexmmo/Code/TheFlaskMegaTutorial-project/lib/python3.9/site-packages/flask/helpers.py", line 318, in url_for
    if endpoint[:1] == ".":
jinja2.exceptions.UndefinedError: 'login' is undefined
2021-01-13 01:32:37,095 INFO: App startup... [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/app/__init__.py:28]
2021-01-13 01:33:50,746 INFO: App startup... [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/app/__init__.py:28]
2021-01-13 01:39:05,317 INFO: App startup... [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/app/__init__.py:28]
2021-01-13 01:40:07,765 INFO: App startup... [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/app/__init__.py:28]
2021-01-14 14:33:06,695 INFO: App startup... [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/app/__init__.py:28]
2021-01-14 14:34:35,819 INFO: App startup... [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/app/__init__.py:28]
2021-01-14 14:34:53,162 INFO: App startup... [in /home/geexmmo/Code/TheFlaskMegaTutorial-project/app/__init__.py:28]
