2020-12-21 15:23:07,051 INFO: App startup... [in /home/geexmmo/Code/grandstream-provision-tool/app/__init__.py:28]
2020-12-21 15:23:09,567 ERROR: Exception on /edit_profile [POST] [in /home/geexmmo/Code/grandstream-provision-tool/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/geexmmo/Code/grandstream-provision-tool/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/geexmmo/Code/grandstream-provision-tool/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/geexmmo/Code/grandstream-provision-tool/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/geexmmo/Code/grandstream-provision-tool/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/geexmmo/Code/grandstream-provision-tool/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geexmmo/Code/grandstream-provision-tool/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geexmmo/Code/grandstream-provision-tool/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/geexmmo/Code/grandstream-provision-tool/app/routes.py", line 82, in edit_profile
    if form.validate_on_submit():
  File "/home/geexmmo/Code/grandstream-provision-tool/lib/python3.9/site-packages/flask_wtf/form.py", line 100, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/geexmmo/Code/grandstream-provision-tool/lib/python3.9/site-packages/wtforms/form.py", line 318, in validate
    return super(Form, self).validate(extra)
  File "/home/geexmmo/Code/grandstream-provision-tool/lib/python3.9/site-packages/wtforms/form.py", line 150, in validate
    if not field.validate(self, extra):
  File "/home/geexmmo/Code/grandstream-provision-tool/lib/python3.9/site-packages/wtforms/fields/core.py", line 226, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/geexmmo/Code/grandstream-provision-tool/lib/python3.9/site-packages/wtforms/fields/core.py", line 246, in _run_validation_chain
    validator(form, self)
  File "/home/geexmmo/Code/grandstream-provision-tool/app/forms.py", line 40, in validate_username
    user = User.query.filter_by(username = self.username.data).firt()
AttributeError: 'BaseQuery' object has no attribute 'firt'
2020-12-21 15:23:23,220 INFO: App startup... [in /home/geexmmo/Code/grandstream-provision-tool/app/__init__.py:28]
2020-12-21 17:37:19,000 INFO: App startup... [in /home/geexmmo/Code/grandstream-provision-tool/app/__init__.py:28]
2020-12-21 17:38:08,783 INFO: App startup... [in /home/geexmmo/Code/grandstream-provision-tool/app/__init__.py:28]
2020-12-21 17:39:03,668 INFO: App startup... [in /home/geexmmo/Code/grandstream-provision-tool/app/__init__.py:28]
2020-12-21 17:50:23,700 INFO: App startup... [in /home/geexmmo/Code/grandstream-provision-tool/app/__init__.py:28]
2020-12-21 17:50:49,856 INFO: App startup... [in /home/geexmmo/Code/grandstream-provision-tool/app/__init__.py:28]
2020-12-21 17:53:58,802 INFO: App startup... [in /home/geexmmo/Code/grandstream-provision-tool/app/__init__.py:28]
2020-12-28 16:33:30,381 INFO: App startup... [in /home/geexmmo/Code/grandstream-provision-tool/app/__init__.py:28]
2020-12-28 16:34:01,333 INFO: App startup... [in /home/geexmmo/Code/grandstream-provision-tool/app/__init__.py:28]
2020-12-28 16:34:14,578 INFO: App startup... [in /home/geexmmo/Code/grandstream-provision-tool/app/__init__.py:28]
2020-12-28 17:07:00,518 INFO: App startup... [in /home/geexmmo/Code/grandstream-provision-tool/app/__init__.py:28]
